config/routes.rb
Rails.application.routes.draw do

  get "pages/home"
  root to: "pages#home"

  get 'users/show'
  get 'users/edit'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :items, only: [ :index, :show, :new, :create, :search ] do
    resources :rents, only: [:new, :create, :destroy, :index]
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :rents, only: [:index, :show, :new, :create, :destroy, :search]
  resources :item_search

  delete '/items/:id', to: "items#destroy", as: 'delete_item'
  get '/items/:id/edit', to: "items#edit", as: 'edit_item'
  patch '/items/:id', to: "items#update"

  resources :users, only: [:show, :edit, :update]
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many :items
  has_many :reviews
  has_many :rents
  mount_uploader :picture, PictureUploader
  after_create :send_welcome_email


  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(current_user)
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    @user.update(user_params)
    redirect_to users_show_path, notice: 'Perfil atualizado!'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to destroy_user_session_path, alert: 'Perfil Apagado!'#mudar para My_itens
  end


  private

  def user_params
     params.require(:user).permit(:firstname, :lastname, :email, :address, :picture)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container text-center">
  <div class="form-mmp">
    <h2>Perfil</h2>
    <%= simple_form_for(@user) do |t| %>
    <div class="form-mmp-field">
      <%= t.input :picture, label: "Adcione uma foto" %>
      <%= t.input :picture_cache, as: :hidden %>
    </div>
    <div class="form-mmp-field">
      <%= t.label 'Nome' %>
      <%= t.text_field :firstname %>
    </div>
    <div class="form-mmp-field">
      <%= t.label 'Sobrenome' %>
      <%= t.text_field :lastname %>
    </div>
    <div class="form-mmp-field">
      <%= t.label 'Email' %>
      <%= t.text_field :email %>
    </div>
    <div class="form-mmp-field">
      <%= t.label 'Endereço' %>
      <%= t.text_field :address %>
    </div>
    <button>Salvar alterações</button>
    <% end %>

    <%= link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } %>
   </div>
</div>

app/views/users/show.html.erb
<div class="profile-header-wrapper">
  <div class="container profile-header-container text-center">
    <div class="profile-header-infos">
      <%= image_tag @user.picture %>
      <h1> <%= @user.firstname %> <%= @user.lastname %></h1>
    </div>
    <div class="tabs">
      <a class="tab active" data-target="#profile">
        <h3>Perfil</h3>
      </a>
      <a class="tab" data-target="#myitems">
        <h3>Meus itens</h3>
      </a>
      <a class="tab" data-target="#myrents">
        <h3>Minhas locações</h3>
      </a>
    </div>
  </div>
</div>
<div class="white-background">
    <div class="container text-center">
      <div class="tab-content" id="profile">
        <div class="container text-center">
          <div class="form-mmp">
            <h2>Perfil</h2>
            <%= simple_form_for(@user) do |t| %>
            <div class="form-mmp-field">
              <%= t.input :picture, label: "Adcione uma foto" %>
              <%= t.input :picture_cache, as: :hidden %>
            </div>
            <div class="form-mmp-field">
              <%= t.label 'Nome' %>
              <%= t.text_field :firstname %>
            </div>
            <div class="form-mmp-field">
              <%= t.label 'Sobrenome' %>
              <%= t.text_field :lastname %>
            </div>
            <div class="form-mmp-field">
              <%= t.label 'Email' %>
              <%= t.text_field :email %>
            </div>
            <div class="form-mmp-field">
              <%= t.label 'Endereço' %>
              <%= t.text_field :address %>
            </div>
            <button>Salvar alterações</button>
            <% end %>
            <%= link_to "Excluir conta", admin_destroy_user_path(@user), method: :delete, data: { confirm: "You sure?" } %>
           </div>
        </div>

      </div>
      <div class="tab-content hidden" id="myitems">
        <div class="row">
          <% @user.items.each do |item| %>
            <div class="col-lg-4 col-md-4 col-xs-12">
              <div class="card text-center">
                  <%= image_tag item.picture, class: "index-photo"%>
                  <h2 class=""><%= item.product_name %></h2>
                  <p><%= item.price %> reais por dia</p>
                  <div class="cta-container">
                    <%= link_to(item_path(item)) do %>
                      <button class="cta" style="background-color:  #22C9BE; width: 50%; color: white;">Detalhes</button>

                    <%= link_to delete_item_path(item), method: :delete do %>
                      <i class="fa fa-trash-o" aria-hidden="true"></i>
                    <%end%>
                    <%= link_to edit_item_path(item) do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    <% end %>
                    <% end %>
                  </div>
              </div>
              </div>
          <% end %>
        </div>
      </div>
      <div class="tab-content hidden" id="myrents">
        <div class="row">
          <% @user.rents.each do |rent| %>
            <div class="col-lg-4 col-md-4 col-xs-12">
              <div class="card text-center">
                <%= image_tag rent.item.picture, class: "index-photo" %>
                <h2> <%= rent.item.product_name %> </h2>
                  <%= link_to(rent_path(rent)) do %>
                    <button class="cta" style="background-color:  #22C9BE; width: 50%; color: white;">Ver mais</button>
                    <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>