config/routes.rb
Rails.application.routes.draw do

  get "pages/home"
  root to: "pages#home"

  get 'users/show'
  get 'users/edit'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :items, only: [ :index, :show, :new, :create, :search ] do
    resources :rents, only: [:new, :create, :destroy, :index]
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :rents, only: [:index, :show, :new, :create, :destroy, :search]
  resources :item_search

  delete '/items/:id', to: "items#destroy", as: 'delete_item'
  get '/items/:id/edit', to: "items#edit", as: 'edit_item'
  patch '/items/:id', to: "items#update"

  resources :users, only: [:show, :edit, :update]
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-distributed">

  <div class="footer-left">

    <h3>Make my party</h3>
    <p class="footer-company-name">Make My Party &copy; 2016</p>
  </div>

  <div class="footer-center">
    <div>
      <i class="fa fa-phone"></i>
      <p style="font-size: 20px;">+55 11 3456-9898</p>
    </div>

    <div>
      <i class="fa fa-envelope"></i>
      <p style="font-size: 20px;"> <a href="mailto:contato@makemyparty.com.br">contato@makemyparty.com.br</a></p>
    </div>

  </div>

  <div class="footer-right">
    <div class="footer-icons">

      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="#"><i class="fa fa-linkedin"></i></a>
      <a href="#"><i class="fa fa-github"></i></a>

    </div>

  </div>

</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="navbar-mmp">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-logo" do %>
    <h1>Make my party</h1>
  <% end %>
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
      <!-- Profile picture and dropdown -->
      <div class="navbar-mmp-item">
        <div class="dropdown">
          <% if user_signed_in? && current_user.facebook_picture_url %>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to users_show_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default:  current_user.email ) %>
              <% end %>
            </li>
            </li>
            <li>
              <%= link_to new_item_path do %>
                <i class="fa fa-plus-circle"></i>  <%= t(".profile", default: "Adicionar item") %>
              <% end %>
            </li>
            <li>
              <%= link_to users_show_path(filter: 'mine') do %>
                <i class="fa fa-diamond"></i>  <%= t(".profile", default: "Meus itens") %>
              <% end %>
            </li>
            <li>
              <%= link_to users_show_path(filter: 'mine') do %>
              <i class="fa fa-shopping-basket"></i>  <%= t(".profile", default: "Minhas Locações") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <div class="navbar-button-log">
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
        <%= link_to t(user_session_path, default: "Login", id: 'login'), user_session_path %>
      </div>
      <!-- Login text link -->
      <div class="navbar-button">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        <%= link_to t(new_user_session_path, default: "Register"), new_user_session_path %>
      </div>
    <% end %>
</div>
</nav>