config/routes.rb
Rails.application.routes.draw do

  get "pages/home"
  root to: "pages#home"

  get 'users/show'
  get 'users/edit'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :items, only: [ :index, :show, :new, :create, :search ] do
    resources :rents, only: [:new, :create, :destroy, :index]
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :rents, only: [:index, :show, :new, :create, :destroy, :search]
  resources :item_search

  delete '/items/:id', to: "items#destroy", as: 'delete_item'
  get '/items/:id/edit', to: "items#edit", as: 'edit_item'
  patch '/items/:id', to: "items#update"

  resources :users, only: [:show, :edit, :update]
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/controllers/item_search_controller.rb
class ItemSearchController < ApplicationController

  def index
    @items = Item.all



  end



# busca por nome, preço categoria



end

app/helpers/item_search_helper.rb
module ItemSearchHelper
end

app/views/item_search/index.html.erb
<%= form_tag(items_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Digite o que procura aqui" %>
<%= submit_tag "Procurar" %>
<% end %>

<% if @items.present? %>
  <p> seus itens</p>
  <% else %>
  <p> Pedimos desculpas, pois não temos <%= params[:search] %> no momento ... </p>
<% end %>

<button> <%= link_to 'VOLTAR', items_path  %> </button>
<button> <%= link_to 'Nova pesquisa', item_search_index_path %> </button>