config/routes.rb
Rails.application.routes.draw do

  get "pages/home"
  root to: "pages#home"

  get 'users/show'
  get 'users/edit'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :items, only: [ :index, :show, :new, :create, :search ] do
    resources :rents, only: [:new, :create, :destroy, :index]
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :rents, only: [:index, :show, :new, :create, :destroy, :search]
  resources :item_search

  delete '/items/:id', to: "items#destroy", as: 'delete_item'
  get '/items/:id/edit', to: "items#edit", as: 'edit_item'
  patch '/items/:id', to: "items#update"

  resources :users, only: [:show, :edit, :update]
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/item.rb
class Item < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_many :reviews
  has_many :rents
  validates :picture, :price, :product_name, :address, presence: true
  after_create :send_new_item_email

  def self.search(search)
    where("product_name ILIKE ?", "%#{search}%")
  end

  private

  def send_new_item_email
    ItemMailer.new_item(self).deliver_now
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def index
    @items = Item.all
    @title = 'Todos os itens'
    if params[:location].present?
      @items = Item.near(params[:location], params[:distance])
    else
      @items = Item.all.order('created_at DESC')
    end
    if params[:filter] == 'mine'
      @items = @items.where(user: current_user)
      @title = 'Meus Itens'
    end
    if params[:search]
      @title = 'Pesquisa Itens'
      if params[:search]
        @items = Item.search(params[:search]).order("created_at DESC")
      else
        @items = Item.all.order('created_at DESC')
      end
    end
    @items = @items.where(user: current_user) if params[:filter] == 'mine'
    @hash = Gmaps4rails.build_markers(@items) do |item, marker|
      marker.lat item.latitude
      marker.lng item.longitude
    end
  end

  def show
    @item = Item.find(params[:id])
    @rent = Rent.new
    @rent.item = @item
    @item_coordinates = { lat: @item.latitude, lng: @item.longitude }
    @rent.user = current_user
    @hash = Gmaps4rails.build_markers(@item) do |item, marker|
      marker.lat item.latitude
      marker.lng item.longitude
    end

    @events = []
    @item.rents.each do |rent|
      @events << {title: 'Reservado', start: rent.initial_date.strftime('%Y-%m-%d'), end: (rent.end_date + 1.day).strftime('%Y-%m-%d')}
    end

    @rents = @item.rents.where(user: current_user)
  end

  def locate(location, distance)
    @item = Item.near(address, radius)
  end

  def search(product_name)
    @item = Item.where(product_name: params[:product_name])
  end

  def new
    @item = Item.new
    @item.user = current_user
  end

  def search
    @item = Item.new
    @item.user = current_user
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save(item_params)
      redirect_to items_path, notice: 'Item Criado!' #mudar para My_itens
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to items_path, notice: 'Item Atualizado!'#mudar para My_itens
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, notice: 'Item Apagado!'#mudar para My_itens
  end

  private

  def item_params
    params.require(:item).permit(:product_name, :description, :price, :category, :address, :picture, :picture_cache)
  end

  def find_item
    @item = Item.find(params[:item_id])
  end

end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/edit.html.erb
<div class="form-mmp text-center">
  <h2>Editar item</h2>
  <%= simple_form_for(@item) do |t| %>
    <div class="form-mmp-field">
      <%= t.label 'Nome do item' %>
      <%= t.text_field :product_name %>
    </div>
    <div class="form-mmp-field">
      <%= t.label 'Descrição' %>
      <%= t.text_area :description %>
    </div>
    <div class="form-mmp-field">
      <%= t.label 'Preço' %>
      <%= t.text_field :price %>
    </div>
    <div class="form-mmp-field">
      <%= t.label 'Endereço' %>
      <%= t.text_field :address %>
    </div>
    <div class="form-mmp-field">
      <%= t.label 'Categoria' %>
      <%= t.text_field :category %>
    </div>
    <div class="form-mmp-field">
      <%= t.input :picture, label: 'Coloque uma foto' %>
      <%= t.input :picture_cache, as: :hidden %>
    </div>
    <button>Salvar</button>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="container-fluid text-center">
  <br>
  <br>
  <br>
  <h2> <%= @title %> </h2>
  <br>
  <br>
  <div class="form-mmp">
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <%= form_tag(items_path, :method => "get", id: "search-form") do %>
        <h3> <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Procurando alguma coisa?</h3>
        <%= text_field_tag :search, params[:search], placeholder: "Digite o item",  class: 'form-mmp-field' %>
      <% end %>
      <br>
    </div>
    <div class="col-xs-12 col-md-6">
      <%= form_tag items_path, method: :get do %>

        <%= text_field_tag :location, params[:location], placeholder: "Itens perto de...", class: "form-mmp-field" %>
        <br>
        <%= text_field_tag :distance, params[:distance], placeholder: "Distância em km", class: "form-mmp-field" %>
        <button>PROCURAR</button>
      <% end %>
    </div>
  </div>

  </div>
  <br>
  <br>
  <% if @items.present? %>
  <p> </p>
    <% else %>
  <p>Item não encontrado: <%= params[:search] %>.</p>
  <% end %>
  <br>
  <div class="row">
      <% @items.each do |item| %>
        <div class="col-lg-4 col-md-4 col-xs-12">
          <div class="card text-center">
              <%= image_tag item.picture, class: "index-photo"%>
              <h2 class=""><%= item.product_name %></h2>
              <p><%= item.price %> reais por dia</p>
              <div class="cta-container">
                <%= link_to(item_path(item)) do %>
                <button class="cta" style="background-color:  #22C9BE; width: 50%; color: white;">Detalhes</button>
                <% end %>
              </div>
          </div>
          </div>
      <% end %>
  </div>
  <br>
  <br>
<br>
<br>
<br>
</div>
<div class="col-xs-12 col-sm-6 col-lg-6" id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/items/mine.html.erb
<h2> Meus items cadastrados</h2>
<br>
<% @items.each do |item| %>
  <p> <h3><%= item.product_name %></h3> </p>
  <p><h4> <%= item.description %> </h4></p>
  <p> <%= item.picture %> </p>

<% end %>

<button> <%= link_to 'NEW', new_item_path  %> </button>

app/views/items/new.html.erb
<div class="form-mmp">
  <h2>Novo item</h2>
  <%= simple_form_for @item do |f| %>
    <div class="form-mmp-field">
      <%= f.input :product_name, label: "Nome do item" %>
    </div>
    <div class="form-mmp-field">
      <%= f.input :description, label: "Descrição", as: :text %>
    </div>
    <div class="form-mmp-field">
      <%= f.input :address, label: 'Endereço'%>
    </div>
    <div class="form-mmp-field">
      <%= f.input :price, label: "Preço do aluguel/dia" %>
    </div>
    <div class="form-mmp-field">
      <%= f.input :picture, label: "Adcione uma foto" %>
      <%= f.input :picture_cache, as: :hidden %>
    </div>
    <button type="submit"> Criar</button>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="container text-center">
  <div class="well well-lg">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-lg-6">
        <br>
        <br>
        <br>
        <%= image_tag @item.picture.url, class: "show-photo", "data-toggle" => "modal" , "data-target" => "#myModal" %>
        <small> <i style="color:grey;">Clique na foto para ver em alta resolução </i></small>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <%= image_tag @item.picture.url %>
          </div>
        </div>
        </div>
      <div class="col-xs-12 col-sm-6 col-lg-6">
        <div class="form-mmp">
          <h2>Reserve agora! </h2>
          <%= simple_form_for [@item, @rent] do |f| %>
          <%= f.input :initial_date, as: :string, required: false,
          :placeholder => 'Select date', input_html: {class: "form-control datepicker"},
          label: "Data de inicio " %>
          <%= f.input :end_date, as: :string, required: false,
          :placeholder => 'Select date', input_html: {class: "form-control datepicker"},
          label: "Data de devolução " %>
          <button type="submit">RESERVAR</button>
        <% end %>
      </div>
    </div>

      <div class="col-xs-12 col-sm-6 col-lg-6">
        <h1 class="product-name"><%= @item.product_name %></h1>
        <div class="form-mmp-field">
          <p>
            <b>Preço (por dia): <br></b><%= @item.price %>
          </p>
          <p>
            <b>Informações sobre o item: <br></b><%= @item.description %>
          </p>
          <p> <b> Categoria: </b> <br><%= @item.category %> </p>
        </div>
      </div>
    </div>
  </div>
  <div id="calendar" class="fullcalendar"></div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <button> <%= link_to 'AVALIE', new_item_review_path(@item)  %> </button>
      </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="well">
      <h3> Avaliações <i class="fa fa-commenting" aria-hidden="true"></i>
 </h3>

        <% @item.reviews.each do |review| %>
          <div class="row">
            <hr>
            <div class="form-mmp">
            <div class="col-xs-12">

          </div>
          <div class="col-xs-12">
            <div class="form-mmp-field">
              <%= image_tag review.user.picture, class: 'avatar-comment' %>
              <p> <b><%= "#{review.user.firstname}"%> </b></p>
              <p> "<%= "#{review.description}"%>" </p>
            </div>
          </div>
          </div>
          <hr>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('#calendar').fullCalendar({
        events: <%= raw @events.to_json %>
      });
    });

  <% end %>
<% end %>

<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>